import { PrismaClient } from '@prisma/client'
const db = new PrismaClient()
const users = await db.user.findMany({ select: { id: true, username: true, email: true, role: true } })
console.log('USERS:', JSON.stringify(users.map(u => ({ u: u.username, e: u.email, r: u.role }))))
const groups = await db.group.findMany({ select: { id: true, name: true, slug: true } })
console.log('GROUPS:', JSON.stringify(groups))
const gm = await db.groupMessage.count()
const dm = await db.directMessage.count()
const convs = await db.directConversation.count()
const notifs = await db.notification.count()
const reports = await db.report.count()
const blocks = await db.block.count()
console.log('COUNTS groupMessages=%d directMessages=%d convs=%d notifs=%d reports=%d blocks=%d', gm, dm, convs, notifs, reports, blocks)
const notifTypes = await db.notification.groupBy({ by: ['type'], _count: true })
console.log('NOTIF TYPES:', JSON.stringify(notifTypes))
await db.$disconnect()
